/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Affiliate', 'model/BadRequest', 'model/Document', 'model/DocumentDocument', 'model/Forbidden', 'model/InternalServerError', 'model/NotFound', 'model/NotImplemented', 'api/DocumentsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Affiliate'), require('./model/BadRequest'), require('./model/Document'), require('./model/DocumentDocument'), require('./model/Forbidden'), require('./model/InternalServerError'), require('./model/NotFound'), require('./model/NotImplemented'), require('./api/DocumentsApi'));
  }
}(function(ApiClient, Affiliate, BadRequest, Document, DocumentDocument, Forbidden, InternalServerError, NotFound, NotImplemented, DocumentsApi) {
  'use strict';

  /**
   * Swagger_documentation_for_Visma_Sign_API_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var VismaSignClient = require('index'); // See note below*.
   * var xxxSvc = new VismaSignClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new VismaSignClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new VismaSignClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new VismaSignClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Affiliate model constructor.
     * @property {module:model/Affiliate}
     */
    Affiliate: Affiliate,
    /**
     * The BadRequest model constructor.
     * @property {module:model/BadRequest}
     */
    BadRequest: BadRequest,
    /**
     * The Document model constructor.
     * @property {module:model/Document}
     */
    Document: Document,
    /**
     * The DocumentDocument model constructor.
     * @property {module:model/DocumentDocument}
     */
    DocumentDocument: DocumentDocument,
    /**
     * The Forbidden model constructor.
     * @property {module:model/Forbidden}
     */
    Forbidden: Forbidden,
    /**
     * The InternalServerError model constructor.
     * @property {module:model/InternalServerError}
     */
    InternalServerError: InternalServerError,
    /**
     * The NotFound model constructor.
     * @property {module:model/NotFound}
     */
    NotFound: NotFound,
    /**
     * The NotImplemented model constructor.
     * @property {module:model/NotImplemented}
     */
    NotImplemented: NotImplemented,
    /**
     * The DocumentsApi service constructor.
     * @property {module:api/DocumentsApi}
     */
    DocumentsApi: DocumentsApi
  };

  return exports;
}));
