/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Affiliate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Affiliate'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.DocumentDocument = factory(root.VismaSignClient.ApiClient, root.VismaSignClient.Affiliate);
  }
}(this, function(ApiClient, Affiliate) {
  'use strict';




  /**
   * The DocumentDocument model module.
   * @module model/DocumentDocument
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>DocumentDocument</code>.
   * Document data
   * @alias module:model/DocumentDocument
   * @class
   * @param name {String} Document name
   */
  var exports = function(name) {
    var _this = this;

    _this['name'] = name;



  };

  /**
   * Constructs a <code>DocumentDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentDocument} obj Optional instance to populate.
   * @return {module:model/DocumentDocument} The populated <code>DocumentDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('category_uuid')) {
        obj['category_uuid'] = ApiClient.convertToType(data['category_uuid'], 'String');
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('affiliates')) {
        obj['affiliates'] = ApiClient.convertToType(data['affiliates'], [Affiliate]);
      }
    }
    return obj;
  }

  /**
   * Document name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Optional, must exist if defined
   * @member {String} category_uuid
   */
  exports.prototype['category_uuid'] = undefined;
  /**
   * Optional, must exist if defined
   * @member {String} category
   */
  exports.prototype['category'] = undefined;
  /**
   * @member {Array.<module:model/Affiliate>} affiliates
   */
  exports.prototype['affiliates'] = undefined;



  return exports;
}));


