/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InviteeGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InviteeGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.InviteeGroups = factory(root.VismaSignClient.ApiClient, root.VismaSignClient.InviteeGroup);
  }
}(this, function(ApiClient, InviteeGroup) {
  'use strict';




  /**
   * The InviteeGroups model module.
   * @module model/InviteeGroups
   * @version 0.0.5
   */

  /**
   * Constructs a new <code>InviteeGroups</code>.
   * @alias module:model/InviteeGroups
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>InviteeGroups</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InviteeGroups} obj Optional instance to populate.
   * @return {module:model/InviteeGroups} The populated <code>InviteeGroups</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('invitee_groups')) {
        obj['invitee_groups'] = ApiClient.convertToType(data['invitee_groups'], [InviteeGroup]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/InviteeGroup>} invitee_groups
   */
  exports.prototype['invitee_groups'] = undefined;



  return exports;
}));


