/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.InvitationCreateMessages = factory(root.VismaSignClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InvitationCreateMessages model module.
   * @module model/InvitationCreateMessages
   * @version 0.0.4
   */

  /**
   * Constructs a new <code>InvitationCreateMessages</code>.
   * @alias module:model/InvitationCreateMessages
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>InvitationCreateMessages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvitationCreateMessages} obj Optional instance to populate.
   * @return {module:model/InvitationCreateMessages} The populated <code>InvitationCreateMessages</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('send_invitation_email')) {
        obj['send_invitation_email'] = ApiClient.convertToType(data['send_invitation_email'], 'Boolean');
      }
      if (data.hasOwnProperty('invitation_email_message')) {
        obj['invitation_email_message'] = ApiClient.convertToType(data['invitation_email_message'], 'String');
      }
      if (data.hasOwnProperty('send_invitation_sms')) {
        obj['send_invitation_sms'] = ApiClient.convertToType(data['send_invitation_sms'], 'Boolean');
      }
      if (data.hasOwnProperty('custom_sms')) {
        obj['custom_sms'] = ApiClient.convertToType(data['custom_sms'], 'String');
      }
      if (data.hasOwnProperty('separate_invite_parts')) {
        obj['separate_invite_parts'] = ApiClient.convertToType(data['separate_invite_parts'], 'Boolean');
      }
      if (data.hasOwnProperty('send_invitee_all_collected_email')) {
        obj['send_invitee_all_collected_email'] = ApiClient.convertToType(data['send_invitee_all_collected_email'], 'Boolean');
      }
      if (data.hasOwnProperty('send_inviter_one_collected_emails')) {
        obj['send_inviter_one_collected_emails'] = ApiClient.convertToType(data['send_inviter_one_collected_emails'], 'Boolean');
      }
      if (data.hasOwnProperty('attachment_allowed')) {
        obj['attachment_allowed'] = ApiClient.convertToType(data['attachment_allowed'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} send_invitation_email
   */
  exports.prototype['send_invitation_email'] = undefined;
  /**
   * @member {String} invitation_email_message
   */
  exports.prototype['invitation_email_message'] = undefined;
  /**
   * @member {Boolean} send_invitation_sms
   */
  exports.prototype['send_invitation_sms'] = undefined;
  /**
   * @member {String} custom_sms
   */
  exports.prototype['custom_sms'] = undefined;
  /**
   * @member {Boolean} separate_invite_parts
   */
  exports.prototype['separate_invite_parts'] = undefined;
  /**
   * @member {Boolean} send_invitee_all_collected_email
   */
  exports.prototype['send_invitee_all_collected_email'] = undefined;
  /**
   * @member {Boolean} send_inviter_one_collected_emails
   */
  exports.prototype['send_inviter_one_collected_emails'] = undefined;
  /**
   * @member {Boolean} attachment_allowed
   */
  exports.prototype['attachment_allowed'] = undefined;



  return exports;
}));


