/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InvitationCreateInviter', 'model/InvitationCreateMessages', 'model/InvitationCreateOrder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InvitationCreateInviter'), require('./InvitationCreateMessages'), require('./InvitationCreateOrder'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.InvitationCreate = factory(root.VismaSignClient.ApiClient, root.VismaSignClient.InvitationCreateInviter, root.VismaSignClient.InvitationCreateMessages, root.VismaSignClient.InvitationCreateOrder);
  }
}(this, function(ApiClient, InvitationCreateInviter, InvitationCreateMessages, InvitationCreateOrder) {
  'use strict';




  /**
   * The InvitationCreate model module.
   * @module model/InvitationCreate
   * @version 0.0.6
   */

  /**
   * Constructs a new <code>InvitationCreate</code>.
   * @alias module:model/InvitationCreate
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>InvitationCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvitationCreate} obj Optional instance to populate.
   * @return {module:model/InvitationCreate} The populated <code>InvitationCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('identifier_type')) {
        obj['identifier_type'] = ApiClient.convertToType(data['identifier_type'], 'String');
      }
      if (data.hasOwnProperty('identifier')) {
        obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
      }
      if (data.hasOwnProperty('sms')) {
        obj['sms'] = ApiClient.convertToType(data['sms'], 'String');
      }
      if (data.hasOwnProperty('sign_as_organization')) {
        obj['sign_as_organization'] = ApiClient.convertToType(data['sign_as_organization'], 'Boolean');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('messages')) {
        obj['messages'] = InvitationCreateMessages.constructFromObject(data['messages']);
      }
      if (data.hasOwnProperty('inviter')) {
        obj['inviter'] = InvitationCreateInviter.constructFromObject(data['inviter']);
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = InvitationCreateOrder.constructFromObject(data['order']);
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} identifier_type
   */
  exports.prototype['identifier_type'] = undefined;
  /**
   * @member {String} identifier
   */
  exports.prototype['identifier'] = undefined;
  /**
   * @member {String} sms
   */
  exports.prototype['sms'] = undefined;
  /**
   * @member {Boolean} sign_as_organization
   */
  exports.prototype['sign_as_organization'] = undefined;
  /**
   * @member {module:model/InvitationCreate.LanguageEnum} language
   */
  exports.prototype['language'] = undefined;
  /**
   * @member {module:model/InvitationCreateMessages} messages
   */
  exports.prototype['messages'] = undefined;
  /**
   * @member {module:model/InvitationCreateInviter} inviter
   */
  exports.prototype['inviter'] = undefined;
  /**
   * @member {module:model/InvitationCreateOrder} order
   */
  exports.prototype['order'] = undefined;


  /**
   * Allowed values for the <code>language</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LanguageEnum = {
    /**
     * value: "fi"
     * @const
     */
    "fi": "fi",
    /**
     * value: "sv"
     * @const
     */
    "sv": "sv",
    /**
     * value: "en"
     * @const
     */
    "en": "en",
    /**
     * value: "nb"
     * @const
     */
    "nb": "nb",
    /**
     * value: "da"
     * @const
     */
    "da": "da"  };


  return exports;
}));


