/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VismaSignClient);
  }
}(this, function(expect, VismaSignClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VismaSignClient.SavedEmailMessage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SavedEmailMessage', function() {
    it('should create an instance of SavedEmailMessage', function() {
      // uncomment below and update the code to test SavedEmailMessage
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be.a(VismaSignClient.SavedEmailMessage);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be();
    });

    it('should have the property editedOn (base name: "edited_on")', function() {
      // uncomment below and update the code to test the property editedOn
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be();
    });

    it('should have the property editedBy (base name: "edited_by")', function() {
      // uncomment below and update the code to test the property editedBy
      //var instane = new VismaSignClient.SavedEmailMessage();
      //expect(instance).to.be();
    });

  });

}));
