/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthenticationMethods', 'model/BadRequest', 'model/Forbidden', 'model/InternalServerError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AuthenticationMethods'), require('../model/BadRequest'), require('../model/Forbidden'), require('../model/InternalServerError'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.AuthenticationsApi = factory(root.VismaSignClient.ApiClient, root.VismaSignClient.AuthenticationMethods, root.VismaSignClient.BadRequest, root.VismaSignClient.Forbidden, root.VismaSignClient.InternalServerError);
  }
}(this, function(ApiClient, AuthenticationMethods, BadRequest, Forbidden, InternalServerError) {
  'use strict';

  /**
   * Authentications service.
   * @module api/AuthenticationsApi
   * @version 0.0.2
   */

  /**
   * Constructs a new AuthenticationsApi. 
   * @alias module:api/AuthenticationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Gets authentication methods
     * Gets authentication methods
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.includeAllIdProviders By default, only Finnish authentication methods are provided. By adding the GET parameter value includeAllIdProviders&#x3D;true to the request, Nordic authentication methods will also be included in the response.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AuthenticationMethods} and HTTP response
     */
    this.getAuthenticationMethodsWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'includeAllIdProviders': opts['includeAllIdProviders'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = AuthenticationMethods;

      return this.apiClient.callApi(
        '/auth/methods', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets authentication methods
     * Gets authentication methods
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.includeAllIdProviders By default, only Finnish authentication methods are provided. By adding the GET parameter value includeAllIdProviders&#x3D;true to the request, Nordic authentication methods will also be included in the response.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AuthenticationMethods}
     */
    this.getAuthenticationMethods = function(opts) {
      return this.getAuthenticationMethodsWithHttpInfo(opts)
        .then(function(response_and_data) {
          if (response_and_data.response.statusCode === 201 && response_and_data.response.headers['location']) {
            return {'location': response_and_data.response.headers['location']};
          }
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
