/**
 * Visma-Sign API
 * Swagger documentation for Visma-Sign API.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BadRequest', 'model/Forbidden', 'model/InternalServerError', 'model/InvitationCreate', 'model/InvitationCreateResponse', 'model/InvitationFullfillment', 'model/InvitationStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BadRequest'), require('../model/Forbidden'), require('../model/InternalServerError'), require('../model/InvitationCreate'), require('../model/InvitationCreateResponse'), require('../model/InvitationFullfillment'), require('../model/InvitationStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.VismaSignClient) {
      root.VismaSignClient = {};
    }
    root.VismaSignClient.InvitationsApi = factory(root.VismaSignClient.ApiClient, root.VismaSignClient.BadRequest, root.VismaSignClient.Forbidden, root.VismaSignClient.InternalServerError, root.VismaSignClient.InvitationCreate, root.VismaSignClient.InvitationCreateResponse, root.VismaSignClient.InvitationFullfillment, root.VismaSignClient.InvitationStatus);
  }
}(this, function(ApiClient, BadRequest, Forbidden, InternalServerError, InvitationCreate, InvitationCreateResponse, InvitationFullfillment, InvitationStatus) {
  'use strict';

  /**
   * Invitations service.
   * @module api/InvitationsApi
   * @version 0.0.1
   */

  /**
   * Constructs a new InvitationsApi. 
   * @alias module:api/InvitationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Create invitations for document
     * Create invitations for document
     * @param {Array.<module:model/InvitationCreate>} body Payload
     * @param {String} documentId document id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/InvitationCreateResponse>} and HTTP response
     */
    this.createDocumentInvitationWithHttpInfo = function(body, documentId) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createDocumentInvitation");
      }

      // verify the required parameter 'documentId' is set
      if (documentId === undefined || documentId === null) {
        throw new Error("Missing the required parameter 'documentId' when calling createDocumentInvitation");
      }


      var pathParams = {
        'documentId': documentId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = [InvitationCreateResponse];

      return this.apiClient.callApi(
        '/document/{documentId}/invitations', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create invitations for document
     * Create invitations for document
     * @param {Array.<module:model/InvitationCreate>} body Payload
     * @param {String} documentId document id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/InvitationCreateResponse>}
     */
    this.createDocumentInvitation = function(body, documentId) {
      return this.createDocumentInvitationWithHttpInfo(body, documentId)
        .then(function(response_and_data) {
          if (response_and_data.response.statusCode === 201 && response_and_data.response.headers['location']) {
            return {'location': response_and_data.response.headers['location']};
          }
          return response_and_data.data;
        });
    }


    /**
     * Fulfills invitation
     * Fulfills invitation
     * @param {module:model/InvitationFullfillment} body Payload
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.fullfillInvitationWithHttpInfo = function(body, invitationId) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling fullfillInvitation");
      }

      // verify the required parameter 'invitationId' is set
      if (invitationId === undefined || invitationId === null) {
        throw new Error("Missing the required parameter 'invitationId' when calling fullfillInvitation");
      }


      var pathParams = {
        'invitationId': invitationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/invitation/{invitationId}/signature', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fulfills invitation
     * Fulfills invitation
     * @param {module:model/InvitationFullfillment} body Payload
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.fullfillInvitation = function(body, invitationId) {
      return this.fullfillInvitationWithHttpInfo(body, invitationId)
        .then(function(response_and_data) {
          if (response_and_data.response.statusCode === 201 && response_and_data.response.headers['location']) {
            return {'location': response_and_data.response.headers['location']};
          }
          return response_and_data.data;
        });
    }


    /**
     * Finds invitation status
     * Finds invitation status
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InvitationStatus} and HTTP response
     */
    this.getInvitationStatusWithHttpInfo = function(invitationId) {
      var postBody = null;

      // verify the required parameter 'invitationId' is set
      if (invitationId === undefined || invitationId === null) {
        throw new Error("Missing the required parameter 'invitationId' when calling getInvitationStatus");
      }


      var pathParams = {
        'invitationId': invitationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = InvitationStatus;

      return this.apiClient.callApi(
        '/invitation/{invitationId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Finds invitation status
     * Finds invitation status
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InvitationStatus}
     */
    this.getInvitationStatus = function(invitationId) {
      return this.getInvitationStatusWithHttpInfo(invitationId)
        .then(function(response_and_data) {
          if (response_and_data.response.statusCode === 201 && response_and_data.response.headers['location']) {
            return {'location': response_and_data.response.headers['location']};
          }
          return response_and_data.data;
        });
    }


    /**
     * Reminds single invitee
     * Reminds single invitee
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.remindSingleInviteeWithHttpInfo = function(invitationId) {
      var postBody = null;

      // verify the required parameter 'invitationId' is set
      if (invitationId === undefined || invitationId === null) {
        throw new Error("Missing the required parameter 'invitationId' when calling remindSingleInvitee");
      }


      var pathParams = {
        'invitationId': invitationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json;charset=utf-8'];
      var accepts = ['application/json;charset=utf-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/invitation/{invitationId}/remind', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Reminds single invitee
     * Reminds single invitee
     * @param {String} invitationId invitation id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.remindSingleInvitee = function(invitationId) {
      return this.remindSingleInviteeWithHttpInfo(invitationId)
        .then(function(response_and_data) {
          if (response_and_data.response.statusCode === 201 && response_and_data.response.headers['location']) {
            return {'location': response_and_data.response.headers['location']};
          }
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
